if RUBY_ENGINE == "opal"
  module Errno
    class EPERM   < SystemCallError; Errno =  1; end
    class ENOENT  < SystemCallError; Errno =  2; end
    class ESRCH   < SystemCallError; Errno =  3; end
    class EINTR   < SystemCallError; Errno =  4; end
    class EIO     < SystemCallError; Errno =  5; end
    class ENXIO   < SystemCallError; Errno =  6; end
    class E2BIG   < SystemCallError; Errno =  7; end
    class ENOEXEC < SystemCallError; Errno =  8; end
    class EBADF   < SystemCallError; Errno =  9; end
    class ECHILD  < SystemCallError; Errno = 10; end
    class EAGAIN  < SystemCallError; Errno = 11; end
    class ENOMEM  < SystemCallError; Errno = 12; end
    class EACCES  < SystemCallError; Errno = 13; end
    class EFAULT  < SystemCallError; Errno = 14; end
    class ENOTBLK < SystemCallError; Errno = 15; end
    class EBUSY   < SystemCallError; Errno = 16; end
    class EEXIST  < SystemCallError; Errno = 17; end
    class EXDEV   < SystemCallError; Errno = 18; end
    class ENODEV  < SystemCallError; Errno = 19; end
    class ENOTDIR < SystemCallError; Errno = 20; end
    class EISDIR  < SystemCallError; Errno = 21; end
    class EINVAL  < SystemCallError; Errno = 22; end
    class ENFILE  < SystemCallError; Errno = 23; end
    class EMFILE  < SystemCallError; Errno = 24; end
    class ENOTTY  < SystemCallError; Errno = 25; end
    class ETXTBSY < SystemCallError; Errno = 26; end
    class EFBIG   < SystemCallError; Errno = 27; end
    class ENOSPC  < SystemCallError; Errno = 28; end
    class ESPIPE  < SystemCallError; Errno = 29; end
    class EROFS   < SystemCallError; Errno = 30; end
    class EMLINK  < SystemCallError; Errno = 31; end
    class EPIPE   < SystemCallError; Errno = 32; end
    class EDOM    < SystemCallError; Errno = 33; end
    class ERANGE  < SystemCallError; Errno = 34; end
    class EDEADLK      < SystemCallError; Errno = 35; end
    class ENAMETOOLONG < SystemCallError; Errno = 36; end
    class ENOLCK       < SystemCallError; Errno = 37; end
    class ENOSYS       < SystemCallError; Errno = 38; end
    class ENOTEMPTY    < SystemCallError; Errno = 39; end
    class ELOOP        < SystemCallError; Errno = 40; end
    class EWOULDBLOCK  < SystemCallError; Errno = EAGAIN::Errno; end
    class ENOMSG       < SystemCallError; Errno = 42; end
    class EIDRM        < SystemCallError; Errno = 43; end
    class ECHRNG       < SystemCallError; Errno = 44; end
    class EL2NSYNC     < SystemCallError; Errno = 45; end
    class EL3HLT       < SystemCallError; Errno = 46; end
    class EL3RST       < SystemCallError; Errno = 47; end
    class ELNRNG       < SystemCallError; Errno = 48; end
    class EUNATCH      < SystemCallError; Errno = 49; end
    class ENOCSI       < SystemCallError; Errno = 50; end
    class EL2HLT       < SystemCallError; Errno = 51; end
    class EBADE        < SystemCallError; Errno = 52; end
    class EBADR        < SystemCallError; Errno = 53; end
    class EXFULL       < SystemCallError; Errno = 54; end
    class ENOANO       < SystemCallError; Errno = 55; end
    class EBADRQC      < SystemCallError; Errno = 56; end
    class EBADSLT      < SystemCallError; Errno = 57; end
    class EDEADLOCK    < SystemCallError; Errno = EDEADLK::Errno; end
    class EBFONT          < SystemCallError; Errno = 59 ; end
    class ENOSTR          < SystemCallError; Errno = 60 ; end
    class ENODATA         < SystemCallError; Errno = 61 ; end
    class ETIME           < SystemCallError; Errno = 62 ; end
    class ENOSR           < SystemCallError; Errno = 63 ; end
    class ENONET          < SystemCallError; Errno = 64 ; end
    class ENOPKG          < SystemCallError; Errno = 65 ; end
    class EREMOTE         < SystemCallError; Errno = 66 ; end
    class ENOLINK         < SystemCallError; Errno = 67 ; end
    class EADV            < SystemCallError; Errno = 68 ; end
    class ESRMNT          < SystemCallError; Errno = 69 ; end
    class ECOMM           < SystemCallError; Errno = 70 ; end
    class EPROTO          < SystemCallError; Errno = 71 ; end
    class EMULTIHOP       < SystemCallError; Errno = 72 ; end
    class EDOTDOT         < SystemCallError; Errno = 73 ; end
    class EBADMSG         < SystemCallError; Errno = 74 ; end
    class EOVERFLOW       < SystemCallError; Errno = 75 ; end
    class ENOTUNIQ        < SystemCallError; Errno = 76 ; end
    class EBADFD          < SystemCallError; Errno = 77 ; end
    class EREMCHG         < SystemCallError; Errno = 78 ; end
    class ELIBACC         < SystemCallError; Errno = 79 ; end
    class ELIBBAD         < SystemCallError; Errno = 80 ; end
    class ELIBSCN         < SystemCallError; Errno = 81 ; end
    class ELIBMAX         < SystemCallError; Errno = 82 ; end
    class ELIBEXEC        < SystemCallError; Errno = 83 ; end
    class EILSEQ          < SystemCallError; Errno = 84 ; end
    class ERESTART        < SystemCallError; Errno = 85 ; end
    class ESTRPIPE        < SystemCallError; Errno = 86 ; end
    class EUSERS          < SystemCallError; Errno = 87 ; end
    class ENOTSOCK        < SystemCallError; Errno = 88 ; end
    class EDESTADDRREQ    < SystemCallError; Errno = 89 ; end
    class EMSGSIZE        < SystemCallError; Errno = 90 ; end
    class EPROTOTYPE      < SystemCallError; Errno = 91 ; end
    class ENOPROTOOPT     < SystemCallError; Errno = 92 ; end
    class EPROTONOSUPPORT < SystemCallError; Errno = 93 ; end
    class ESOCKTNOSUPPORT < SystemCallError; Errno = 94 ; end
    class EOPNOTSUPP      < SystemCallError; Errno = 95 ; end
    class EPFNOSUPPORT    < SystemCallError; Errno = 96 ; end
    class EAFNOSUPPORT    < SystemCallError; Errno = 97 ; end
    class EADDRINUSE      < SystemCallError; Errno = 98 ; end
    class EADDRNOTAVAIL   < SystemCallError; Errno = 99 ; end
    class ENETDOWN        < SystemCallError; Errno = 100; end
    class ENETUNREACH     < SystemCallError; Errno = 101; end
    class ENETRESET       < SystemCallError; Errno = 102; end
    class ECONNABORTED    < SystemCallError; Errno = 103; end
    class ECONNRESET      < SystemCallError; Errno = 104; end
    class ENOBUFS         < SystemCallError; Errno = 105; end
    class EISCONN         < SystemCallError; Errno = 106; end
    class ENOTCONN        < SystemCallError; Errno = 107; end
    class ESHUTDOWN       < SystemCallError; Errno = 108; end
    class ETOOMANYREFS    < SystemCallError; Errno = 109; end
    class ETIMEDOUT       < SystemCallError; Errno = 110; end
    class ECONNREFUSED    < SystemCallError; Errno = 111; end
    class EHOSTDOWN       < SystemCallError; Errno = 112; end
    class EHOSTUNREACH    < SystemCallError; Errno = 113; end
    class EALREADY        < SystemCallError; Errno = 114; end
    class EINPROGRESS     < SystemCallError; Errno = 115; end
    class ESTALE          < SystemCallError; Errno = 116; end
    class EUCLEAN         < SystemCallError; Errno = 117; end
    class ENOTNAM         < SystemCallError; Errno = 118; end
    class ENAVAIL         < SystemCallError; Errno = 119; end
    class EISNAM          < SystemCallError; Errno = 120; end
    class EREMOTEIO       < SystemCallError; Errno = 121; end
    class EDQUOT          < SystemCallError; Errno = 122; end
    class ENOMEDIUM       < SystemCallError; Errno = 123; end
    class EMEDIUMTYPE     < SystemCallError; Errno = 124; end
    class ECANCELED       < SystemCallError; Errno = 125; end
    class ENOKEY          < SystemCallError; Errno = 126; end
    class EKEYEXPIRED     < SystemCallError; Errno = 127; end
    class EKEYREVOKED     < SystemCallError; Errno = 128; end
    class EKEYREJECTED    < SystemCallError; Errno = 129; end
    class EOWNERDEAD      < SystemCallError; Errno = 130; end
    class ENOTRECOVERABLE < SystemCallError; Errno = 131; end
    class ERFKILL         < SystemCallError; Errno = 132; end
    class EHWPOISON       < SystemCallError; Errno = 133; end
  end
end
